# Generated by Django 4.2.5 on 2023-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='entry_date',
            field=models.DateField(),
        ),
    ]
