# Generated by Django 4.1.7 on 2023-09-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coin_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='dollar_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='entry_price',
            field=models.FloatField(),
        ),
    ]
