# Generated by Django 4.1.7 on 2023-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_coin_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coin_value',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='dollar_value',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='entry_price',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='type_position',
            field=models.CharField(max_length=20),
        ),
    ]
