# Generated by Django 4.1.7 on 2023-09-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_coin_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='coin_value',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='dollar_value',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='entry_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
